_extends: .github
repository:
  name: eslint-config-vitest
  description: shareable config for ESLint for Vitest test files
  private: false
  homepage: https://npm.im/@form8ion/eslint-config-vitest
branches:
  - name: master
    protection: null
rulesets:
  - name: prevent destruction of the default branch
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: deletion
      - type: non_fast_forward
